ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'ADMIN_MASTER';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'ADMIN_LIMITED';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'TRAFFIC_MANAGER';

ALTER TYPE "MemberRole" ADD VALUE IF NOT EXISTS 'CLIENT';
